-- certificate_requests.sql
--
-- Self-service certificate requests for examinees who appeared in a past
-- exam. Verify identity -> confirm shipping address -> pay 200 BDT via
-- SSLCommerz -> admin prints a mail label and marks the request posted
-- (which triggers the certificate_posted email).
--
-- Mirrors registrations.payment_* columns for the SSLCommerz lifecycle
-- and adds structured shipping fields + a requested/posted status.
--
-- Apply with:
--   mysql -u nattest_reg -p nattest_regs < schema/certificate_requests.sql
--
-- Idempotent: CREATE TABLE IF NOT EXISTS + ALTER MODIFY on ENUM is safe
-- to re-run.

START TRANSACTION;

CREATE TABLE IF NOT EXISTS certificate_requests (
    id                             CHAR(36)      NOT NULL COMMENT 'UUID v4, generated by PHP',
    registration_id                VARCHAR(36)   NOT NULL COMMENT 'FK -> registrations.id',
    exam_date_id                   CHAR(36)      NOT NULL COMMENT 'FK -> exam_dates.id',
    reg_no                         VARCHAR(20)   NOT NULL COMMENT 'Examinee number via registration_sheet_numbers',

    -- Structured shipping address (captured on the form; recipient_name
    -- and recipient_phone are pre-filled from registrations).
    recipient_name                 VARCHAR(200)  NOT NULL,
    recipient_phone                VARCHAR(20)   NOT NULL,
    house_street                   VARCHAR(300)  NOT NULL,
    area_thana                     VARCHAR(200)  NOT NULL,
    district                       VARCHAR(100)  NOT NULL,
    postal_code                    VARCHAR(20)   NULL,

    -- Payment (mirrors registrations columns; tran_id prefix is 'CRT').
    amount                         DECIMAL(10,2) NOT NULL DEFAULT 200.00,
    payment_status                 ENUM('unpaid','paid','failed','refunded') NOT NULL DEFAULT 'unpaid',
    sslcommerz_transaction_id      VARCHAR(100)  NULL,
    sslcommerz_session_id          VARCHAR(100)  NULL,
    sslcommerz_bank_transaction_id VARCHAR(100)  NULL,
    payment_time                   DATETIME      NULL,

    -- Certificate lifecycle.
    certificate_status             ENUM('requested','posted') NOT NULL DEFAULT 'requested',
    posted_at                      TIMESTAMP     NULL,
    posted_by                      INT           NULL COMMENT 'FK -> admin_users.id',
    tracking_number                VARCHAR(100)  NULL,

    -- Audit.
    ip_address                     VARCHAR(45)   NULL,
    created_at                     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    INDEX idx_cr_registration (registration_id),
    INDEX idx_cr_exam_date (exam_date_id),
    INDEX idx_cr_reg_no (reg_no),
    INDEX idx_cr_payment_status (payment_status),
    INDEX idx_cr_certificate_status (certificate_status),
    INDEX idx_cr_sslcz_tran (sslcommerz_transaction_id),

    CONSTRAINT fk_cr_reg    FOREIGN KEY (registration_id)
        REFERENCES registrations(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_exam   FOREIGN KEY (exam_date_id)
        REFERENCES exam_dates(id) ON DELETE CASCADE,
    CONSTRAINT fk_cr_poster FOREIGN KEY (posted_by)
        REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  COMMENT='Certificate requests with 200 BDT shipping payment, linked to a past-exam examinee';

-- Widen email_log.email_type to include the two new certificate types.
-- ALTER MODIFY on ENUM is idempotent if the values already match.
ALTER TABLE email_log
    MODIFY email_type ENUM(
        'confirmation', 'rejection', 'admission_ticket', 'resend',
        'submission_receipt', 'payment_confirmation', 'score_report',
        'certificate_requested', 'certificate_posted'
    ) NOT NULL;

COMMIT;

-- Sanity check.
SELECT
    (SELECT COUNT(*) FROM information_schema.tables
       WHERE table_schema = DATABASE()
         AND table_name = 'certificate_requests') AS table_ok,
    (SELECT COUNT(*) FROM information_schema.columns
       WHERE table_schema = DATABASE()
         AND table_name = 'email_log'
         AND column_name = 'email_type'
         AND data_type   = 'enum') AS email_log_type_ok;
