-- Exam Dates Database Schema for MySQL
-- Run this script on the target MySQL database
-- Usage: mysql -u username -p database_name < create_exam_dates_mysql.sql

-- Create exam_dates table
-- Note: ID should be auto-generated UUID using str(uuid.uuid4())
CREATE TABLE IF NOT EXISTS exam_dates (
    id CHAR(36) PRIMARY KEY COMMENT 'UUID generated by application',
    exam_date DATE NOT NULL,
    registration_deadline DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create exam_levels table (junction table for many-to-many relationship)
-- registration_cap: NULL = unlimited, 0 = closed, N = max paid registrations
CREATE TABLE IF NOT EXISTS exam_levels (
    exam_date_id CHAR(36) NOT NULL,
    level ENUM('1Q/N1', '2Q/N2', '3Q/N3', '4Q/N4', '5Q/N5') NOT NULL,
    registration_cap INT UNSIGNED NULL DEFAULT NULL
        COMMENT 'Max paid registrations allowed for this (exam_date, level). NULL = unlimited.',
    PRIMARY KEY (exam_date_id, level),
    FOREIGN KEY (exam_date_id) REFERENCES exam_dates(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Create index for exam_date queries
CREATE INDEX idx_exam_dates_date ON exam_dates(exam_date);

-- Sample data (optional - uncomment to insert test data)
/*
INSERT INTO exam_dates (id, exam_date, registration_deadline) VALUES
    ('exam-001', '2026-07-15', '2026-06-30'),
    ('exam-002', '2026-08-20', '2026-07-31');

INSERT INTO exam_levels (exam_date_id, level) VALUES
    ('exam-001', '1Q/N1'),
    ('exam-001', '2Q/N2'),
    ('exam-001', '3Q/N3'),
    ('exam-002', '4Q/N4'),
    ('exam-002', '5Q/N5');
*/

-- Verify tables were created
SELECT CONCAT('exam_dates table created: ', COUNT(*)) as message FROM exam_dates;
SELECT CONCAT('exam_levels table created: ', COUNT(*)) as message FROM exam_levels;
